### ISSUE TITLE
unable to run the birds app

### ISSUE THREAD

**Issue by Magistern** [movidius/ncappzoo#341]
When I run the birds app (`make run`) I just get an error saying:
```bash
Intel OpenVINO environment is already set!
python3 ./birds.py

Please make sure your OpenVINO environment variables are set by sourcing the setupvars.sh script found in <your OpenVINO install location>/bin/ folder.

make: *** [run_py] Error 1
```
What can be the problem?

**Comment by Magistern** [comment]
Also, most of the examples in the appzoo requires apt-get so I guess I cannot run them on a mac
```bash
 pip install pigpio
Collecting pigpio
  Downloading https://files.pythonhosted.org/packages/fc/3e/80b615a713e4cb9816a59227b0776a27ebc0d7847e3de6a043ce9b1f63d2/pigpio-1.44-py2.py3-none-any.whl
Installing collected packages: pigpio
Successfully installed pigpio-1.44
mackojo:gesture_piarm kojo$ make run

Gesture Piarm: Checking application requirements...

Installing Pigpio and it's python library...
sudo apt-get install pigpio
sudo: apt-get: command not found
make: *** [install-reqs] Error 1
```

**Comment by DrewBearly** [comment]
Hello! Thank you for bringing this up! And sorry for the late response, holidays got in the way.

As stated in the README: "The projects in the ncappzoo are tested and known to work on the **Ubuntu 16.04**".

Currently, we only test the apps on Ubuntu 16.04 and Ubuntu 18.04 (18.04 will be added in soon as fully compatible). The macOS Xcode Command Line tools, which include a _make_ tool, are similar to the GNU toolchain tools such as GNU _make_, but are different enough to cause issues such as not holding over some environment variables when using them (at least, in our experience.) You can set up a macOS system to use the GNU tools, but we have not tested this yet and do not recommend it as of now. 

We do strive for expanding our compatibilty. If you want to get to it before we do, you should submit a PR for expanding system support!

I'll close this for now.
