### ISSUE TITLE
Link error in gender_age app

### ISSUE THREAD

**Issue by ggalan87** [movidius/ncappzoo#343]
I tried to run gender_age app, however I got OpenCV link errors. As I realised the error caused because cmake found system's opencv rather than the specific provided by openvino. The issue can be fixed by adding the HINT keyword right before the path in 'find_library' commands below:

https://github.com/movidius/ncappzoo/blob/b63b650e6525cf869d0c7e09ce2168371c020ad4/apps/gender_age/CMakeLists.txt#L19-L23

This guides cmake to look first to the correct path.

**Comment by DrewBearly** [comment]
Thanks for pointing this out! I'll try to fix this this week. 

If you want to contribute further, submit the changes yourself before I do!

**Comment by tomepetty** [comment]
Added a fix in this PR: https://github.com/movidius/ncappzoo/pull/355
